### ISSUE TITLE
List styling on subject tag pages

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#107]
No bullet points needed.

http://localhost:8000/exist/apps/hsg-shell/tags/human-rights

![image](https://cloud.githubusercontent.com/assets/607433/13184083/2aeda774-d73a-11e5-97f9-d0a7787cdb06.png)

**Comment by plutonik-a** [comment]
Partly fixed with https://github.com/eXistSolutions/hsg-shell/commit/88aaeeffcf6edfb290e78b293aea116b63e6a33a

On following 3 pages, there are still lists with bullets. 
I couldn't find any place in the code, where to fix it.

1. [http://localhost:8080/exist/apps/hsg-shell/tags/global-issues](http://localhost:8080/exist/apps/hsg-shell/tags/global-issues)
2. [http://localhost:8080/exist/apps/hsg-shell/tags/department-of-state](http://localhost:8080/exist/apps/hsg-shell/tags/department-of-state)
3. [http://localhost:8080/exist/apps/hsg-shell/tags/politico-military-issues](http://localhost:8080/exist/apps/hsg-shell/tags/politico-military-issues)

Although, one hint might be useful: 
For example (2.), on the overview page of topics [https://history.state.gov/tags/topics](https://history.state.gov/tags/topics) you can see the headline "Department of State (148)", which is supposed to mean, that 148 tagged items where found. 
On the page [https://history.state.gov/tags/department-of-state](https://history.state.gov/tags/department-of-state)   itself it says "No resources have been specifically identified as “Department of State, ..." 
This looks odd - and on our development page, exactly those lists, where no tagged items were found, are still without my fix with class "list-unstyled".
 
In addition, I found this overview list [http://localhost:8080/exist/apps/hsg-shell/milestones/all
](http://localhost:8080/exist/apps/hsg-shell/milestones/all)  still with bullets.
I fixed it according to the original [https://history.state.gov/milestones/all
](https://history.state.gov/milestones/all)

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/3ca37aa4874e56bab50fce0f52fd18b5f589e072
