### ISSUE TITLE
frus:attachment not handled by transform

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#124]
On the following page the raw TEI seems to be passed through into the HTML, thus resulting in bad styling. We probably need to handle the frus:attachment tag wrapped around this stuff:

http://192.168.2.107:8000/exist/apps/hsg-shell/historicaldocuments/frus1952-54v02p1/d7

![image](https://cloud.githubusercontent.com/assets/607433/13399809/60462572-df05-11e5-9ef9-071ee601629d.png)

**Comment by wolfgangmm** [comment]
frus:attachment now transformed into section:

![image](https://cloud.githubusercontent.com/assets/607433/13424857/850d1926-dfa3-11e5-88c3-7885224c63f6.png)

**Comment by joewiz** [comment]
This looks like a good solution, from a code perspective - but could you please add a screenshot showing the appearance? On the current site we render `<frus:attachment>` as an HTML `<div>` and its child head as `<h3>` - same as the parent document's heading styling. It needn't actually be identical, just not *much* smaller. All features of a FRUS document may appear inside an attachment, except further attachments.

For additional context, `<frus:attachment>` is defined in the FRUS ODD as https://github.com/HistoryAtState/frus/blob/master/schema/frus.odd#L892. Its purpose is to allow us to identify attachments/tabs/enclosures within a document, and add some constraints specific to this feature, including forcing them to be located only at the end of a document div (like a `<closer>` element, but not simply a "p.s." or a signature).

**Comment by wolfgangmm** [comment]
Now displays as follows:

![image](https://cloud.githubusercontent.com/assets/607433/13823482/06d11400-ebaa-11e5-8e4b-ead68268f491.png)

**Comment by joewiz** [comment]
This looks great, except I notice that the headings are sans serif - whereas all FRUS body content should be serifed. This appears related to https://github.com/eXistSolutions/hsg-shell/commit/e4903c85bb363fe5689b66420a2d6bddc9f3ec9c. Could you look into this please?

**Comment by wolfgangmm** [comment]
@joewiz so you are saying that the heading in the attachment should not be sans serif because it is in the body content? I'm a bit confused because the main headings are now always sans serif. But we can change the font for the attachment using css.

**Comment by joewiz** [comment]
@wolfgangmm I've never been entirely thrilled about sans-serif but was willing to give it a try, particularly for smaller elements like navbar, breadcrumbs, footer, sidebars, pop-ups, etc. FRUS, in particular, has always been a sans-serif publication, so I instinctively bristle a bit at the sight of serif fonts there, and I suspect my colleagues and some of our readers would too. The U.S. web design standards page about [typography and font pairings](https://playbook.cio.gov/designstandards/visual-style/) has this as a description for all-Meriweather - a good description of the characteristics my office portrays:

> The most formal of the options, this pairing uses Merriweather for both headings and body text. The full suite of serif styles communicates **trustworthiness**, while Merriweather’s contemporary shapes convey freshness and a modern relevance. The weights are designed to pair together for easy reading and clean page design. Light use of Source Sans Pro suggested for legibility of small text needs.
> 
> Recommended applications: sites which need to convey **reliability** and **trust**; basic and text heavy sites.

(My emphasis.) This said, I haven't brought this up since a conversation with Joern about this in, say, November, when I said I'd be alright with trying out sans-serif for headings, and this would be rather late for a change. So for consistency's sake, let's try this for now and likely through the beta period. I'll begin asking for feedback on this point and will let you know if we want to switch document bodies to serif, limiting sans-serif to chrome surrounding the body.

**Comment by joewiz** [comment]
I also really like the look of the new homepage, and the sans serif headers elsewhere have definitely grown on me. So I like it and wouldn't roll it back wholesale; the question is just about document bodies (and their headers).
