### ISSUE TITLE
FRUS TOC too indented; align with volume info above

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#132]
On FRUS landing pages like http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v26, note how the TOC is indented more than the other titles, editors, etc. (see "2015" vs. "About the Series"):

> ![screen shot 2016-03-04 at 3 16 55 am](https://cloud.githubusercontent.com/assets/59118/13521587/b21a76d2-e1b7-11e5-973b-9e4d95863ae1.png)

Please pull the TOC flush left, as on https://history.state.gov/historicaldocuments/frus1977-80v26:

> ![screen shot 2016-03-04 at 3 19 01 am](https://cloud.githubusercontent.com/assets/59118/13521608/e4edd82e-e1b7-11e5-9cb2-b8aa291b2328.png)

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/2fc17b6f3ea8800dfe1a218f3b16eba675447347

**Comment by joewiz** [comment]
Thank you, @plutonik-a! Could you please post a screenshot showing the revised appearance of the page in question, if it's not too inconvenient?

**Comment by plutonik-a** [comment]
Also fixed with https://github.com/eXistSolutions/hsg-shell/commit/017b42a0bf10e71bcdd665fb2ea7779d63943d01

Current state in [http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v26](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v26):

<img width="608" alt="historicaldocuments-frus1977-80v26" src="https://cloud.githubusercontent.com/assets/1157669/13533901/daf988e2-e232-11e5-8f45-b839ca05e552.png">
