### ISSUE TITLE
[frus] Sidebar is missing

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#157]
I wonder, if this sidebar navigation is really missing, or it was intentionally not implemented.
[https://history.state.gov/historicaldocuments/about-frus](https://history.state.gov/historicaldocuments/about-frus)
[https://history.state.gov/beta/historicaldocuments/about-frus](https://history.state.gov/beta/historicaldocuments/about-frus)

<img width="933" alt="missing-panel" src="https://cloud.githubusercontent.com/assets/1157669/13984009/c43f7a7e-f0f3-11e5-87b5-cb172fd456e2.png">

**Comment by joewiz** [comment]
@plutonik-a Good point. I think some navigational aid is needed on this page. Just adapting the old set of dropdowns is problematic, since the volumes dropdown was getting unwieldy and was expensive to generate (from a database perspective). The administrations dropdown didn't have this problem, but is a dropdown awkward in the new design for sidebar panels? As an alternative to an administrations dropdown, a sidebar here could show either (1) a link back to the main page, which shows the administration links front and center or (2) a list of links to each administration grouping. I'm alright with either.

**Comment by plutonik-a** [comment]
I suggest, a sidebar with a link list is the best solution. A dropdown is also just a list, with the disadvantage of one more click for the user.
For the mobile layout, we should plan to use accordions that expand or hide the navigation in milestone-2.

Now to my questions:
1. What do you mean with "administration links front and center"?
2. If I would like to implement the volume list (which you disabled on the current site) in the sidebar, where can I find the links or the list of volumes? 
I am still lost in the site sometimes, because of the many navigation levels and the amount of content...

**Comment by joewiz** [comment]
Great, a sidebar with a link list sounds good.

1. I mean that the images of presidents on the /historicaldocuments landing page are links to the administration listings.

2. You can generate the list of volumes with `@data-template="frus:volumes"`, or using the following query in eXide (apologies for the dummy parameters):

```xquery
xquery version "3.0";

import module namespace fh = "http://history.state.gov/ns/site/hsg/frus-html" at "/db/apps/hsg-shell/modules/frus-html.xqm";

fh:volumes(<blah/>, map {}, ())
```

**Comment by plutonik-a** [comment]
Administration sidebar fixed with https://github.com/eXistSolutions/hsg-shell/pull/156/commits/cc52cae91930e2bfce4250c2a88990b6c934f0fb
