### ISSUE TITLE
[countries] Two <h1> headings on countries article page

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#168]
At the end of each country article, the heading "Resources" is marked as `<h1>`.

For example in:
[https://history.state.gov/beta/countries/afghanistan](https://history.state.gov/beta/countries/afghanistan)

<img width="1150" alt="h1-countries-article" src="https://cloud.githubusercontent.com/assets/1157669/14050240/db502c54-f2ba-11e5-94f1-6dae4d758ac8.png">

I can't find the module, where the code for the article is built. The only hint is `pages:view` in `pages.xqm` which doesn't seem to provide the heading itself...

---
Files:
`pages/countries/article.html`

---
Related https://github.com/eXistSolutions/hsg-shell/issues/108

**Comment by joewiz** [comment]
Hmm, the source XML is here: https://github.com/HistoryAtState/rdcr/blob/master/articles/afghanistan.xml. Does this explain why?

**Comment by tuurma** [comment]
Looks like all first-level div heads get rendered into h1, e.g.
https://github.com/HistoryAtState/rdcr/blob/master/articles/afghanistan.xml#L39
or
https://github.com/HistoryAtState/rdcr/blob/master/articles/afghanistan.xml#L52

**Comment by joewiz** [comment]
The fix is to use Wolfgang's new `heading-offset` parameter (see https://github.com/eXistSolutions/hsg-shell/commit/95121a2223b1c39fc3e642ad75bc69effdea69f8#commitcomment-16731733):

    <div class="hsg-width-two-thirds">
        <div id="content-inner" data-template="app:fix-links">
            <div class="content" data-template="pages:view" data-template-heading-offset="1"/>
        </div>
    </div>

This results in the top-level div heads being transformed into `<h2>` instead of `<h1>` (and all inner heads being adjusted accordingly, by one):

> <img width="402" alt="screen shot 2016-03-29 at 10 45 35 am" src="https://cloud.githubusercontent.com/assets/59118/14112131/78872e7c-f59b-11e5-94e9-004e1722cf5d.png">

**Comment by joewiz** [comment]
Speaking of `<h1>`, page is a little weird, in that it lacks a proper `<h1>`. This is because the source TEI places the article title in the teiHeader instead of in the body of the document (see https://github.com/HistoryAtState/rdcr/blob/master/articles/afghanistan.xml#L7). I have a fix which inserts a new `<h1>` in the `article.html` template just before the body div. 

@plutonik-a Is it a problem that the `<h1>` is outside the `<div class="content">`?

Markup:

> <img width="339" alt="screen shot 2016-03-29 at 10 51 47 am" src="https://cloud.githubusercontent.com/assets/59118/14112343/607c57e8-f59c-11e5-95e1-f9db3018017a.png">

Appearance:

> <img width="557" alt="screen shot 2016-03-29 at 10 51 55 am" src="https://cloud.githubusercontent.com/assets/59118/14112355/68a5efc4-f59c-11e5-8407-8dd9f7486cce.png">

If this is ok with you, I will commit it; but if this is a problem, we will need to consider alternate mechanisms for inserting the title, either via templating or by modifying the source TEI.

**Comment by plutonik-a** [comment]
@joewiz 
> Is it a problem that the `<h1>` is outside the `<div class="content">`?

No, I don't think that this is a problem as long as it stays within the container `class="hsg-width-two-thirds"`, which wraps the whole main content except for the sidebar.

**Comment by joewiz** [comment]
Great, thanks. I think my commit above fixes both issues we've discussed here?
