### ISSUE TITLE
Paths in Frus-TOC sidebar links are wrong 

### ISSUE THREAD

**Issue by plutonik-a** [eXistSolutions/hsg-shell#172]
### Can be checked on Branch "fix-grid-layout"

For example:
[http://localhost:8080/exist/apps/hsg-shell/milestones/1784-1800/convention-and-ratification](http://localhost:8080/exist/apps/hsg-shell/milestones/1784-1800/convention-and-ratification)

The first link in the sidebar is `http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/$app/historicaldocuments/frus-history/epigraph`.

Apparently, some elements are duplicated in the path.
 `$app/historicaldocuments/frus-history/`
Should be [http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/epigraph](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus-history/epigraph)

I couldn't find the right piece of code to be fixed in the sidebar module in file `modules/frus-toc-html.xqm`, because nothings points to the url or `<a>` tag here.

```
declare function toc:prepare-sidebar-toc-list($nodes as node()*) {
    for $node in $nodes
    return
        typeswitch ( $node )
            case element( ul ) return <ul class="hsg-list-group">{toc:prepare-sidebar-toc-list($node/node())}</ul>
            case element( li ) return <li class="hsg-list-group-item">{toc:prepare-sidebar-toc-list($node/node())}</li>
            default return $node
};
```

**Comment by joewiz** [comment]
I realize the approach requires you to add an extra `<div>` wrapper, and this is not ideal. Before settling on this approach I did try to add `app:fix-links` to the parent `<aside>` in https://github.com/eXistSolutions/hsg-shell/blob/master/modules/frus-toc-html.xqm#L35, but the templating system wasn't applying the directive. To force `app:fix-link`'s behavior in XQuery, I remembered `app:fix-this-link()`, which I created for this need (see https://github.com/eXistSolutions/hsg-shell/blob/master/modules/app.xqm#L43-L50; see other uses of this function in XQuery and in templating code at https://github.com/eXistSolutions/hsg-shell/search?utf8=%E2%9C%93&q=app%3Afix-this-link). But since this leads to multiple invocations of the function, once per link, overall I think this may not perform as well as a single call on an outer function. But @wolfgangmm or @tuurma, who are the experts in the templating system, may be able to suggest which solution performs best.

**Comment by plutonik-a** [comment]
I see, this is very tricky. I already noticed, that every element that contains links, needs a wrapper that calls the fix-links function, but didn't realize, that this was missing in this case.

It seems, the call of the handle-the-link-function has to be done earlier in the process, possibly by a link-module, that will be called by the sidebar-module and not at this late stage by the template, where a wrapper is needed to do the job.

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/d2dc3643d0a35df1175ba70b26060c1917803c9e
