### ISSUE TITLE
[frus] Links to WorldCat editions for non-fulltext volumes are missing

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#232]
We provide links to libraries in the case of volumes that we don't have in full text form. We store these in each volume's metadata, in `/db/apps/frus/bibliography`, e.g., https://github.com/HistoryAtState/frus/blob/master/bibliography/frus1958-60v03mSupp.xml#L8:

```xml
<location loc="worldcat">http://worldcat.org/oclc/37817548</location>
```

The links to WorldCat aren't being shown on pages such as https://history.state.gov/historicaldocuments/frus1961-63v22-24mSupp:

> ![screen shot 2016-05-20 at 11 40 15 am](https://cloud.githubusercontent.com/assets/59118/15433335/ee9bc976-1e7f-11e6-889c-f028033bdf30.png)

Here's how they looked on the old site:

> ![screen shot 2016-05-20 at 11 40 07 am](https://cloud.githubusercontent.com/assets/59118/15433338/f678b0fa-1e7f-11e6-9a5e-dd7d4e2cb4c2.png)

**Comment by plutonik-a** [comment]
Related:
https://github.com/eXistSolutions/hsg-shell/issues/154
https://github.com/eXistSolutions/hsg-shell/issues/154#issuecomment-225885068

**Comment by plutonik-a** [comment]
@joewiz 
With my fix https://github.com/eXistSolutions/hsg-shell/commit/ec01c5c699cf3e386ebc48989ac29aeaabe02521, the link to UW Madison is now displayed.
Referring to my comment https://github.com/eXistSolutions/hsg-shell/issues/154#issuecomment-225885068: How do we decide which one of the links is displayed?

<img width="500" alt="bildschirmfoto 2016-06-17 um 13 21 12" src="https://cloud.githubusercontent.com/assets/1157669/16149120/c2d27824-348e-11e6-95ba-1fcd54daf823.png">

**Comment by joewiz** [comment]
We should show any available links to Madison and WorldCat if we don't have the full TEI text of the volume. Typically we don't have both links, only one. The most common type of volume with WorldCat links are the "microfiche supplement" volumes, e.g., https://history.state.gov/historicaldocuments/frus1961-63v13-15mSupp. The link is stored in https://github.com/HistoryAtState/frus/blob/master/bibliography/frus1961-63v13-15mSupp.xml#L8. 

The following query returns the 6 volumes that have links to both Madison and WorldCat:

```xquery
collection('/db/apps/frus/bibliography')/volume[location[@loc = "madison"] ne '' and location[@loc = "worldcat"] ne '']
```

These are: frus1862, frus1864p4, frus1894app1, frus1894app2, frus1901China, and frus1902app1.

**Comment by plutonik-a** [comment]
I fixed this issue despite its lower priority, because it's related to https://github.com/eXistSolutions/hsg-shell/issues/154 and deals with the same part of the code.

Now, all available links for non-fulltext volumes are displayed, which currently applies to volumes frus1862, frus1864p4, frus1894app1, frus1894app2, frus1901China, and frus1902app1.
(i.e. [http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1864p4](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1864p4))

All other non-fulltext volumes will display either a "WorldCat" or a "Madison" link.
(i.e. [http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1961-63v22-24mSupp](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1961-63v22-24mSupp))

<img width="393" alt="bildschirmfoto 2016-08-05 um 18 56 36" src="https://cloud.githubusercontent.com/assets/1157669/17444475/6941ad60-5b40-11e6-8c1e-835cdf0e422c.png">

**Comment by joewiz** [comment]
@plutonik-a Great, thank you!

**Comment by joewiz** [comment]
@plutonik-a Looks great, thank you!

**Comment by plutonik-a** [comment]
I noticed that my previous fix was not sufficient, so I updated the check, if a link is available:

**Before: An empty link**
[https://history.state.gov/historicaldocuments/frus1861](https://history.state.gov/historicaldocuments/frus1861

)<img width="410" alt="bildschirmfoto 2016-08-10 um 19 12 41" src="https://cloud.githubusercontent.com/assets/1157669/17563462/c67bc626-5f2f-11e6-90dd-3fd9e3fb499b.png">

**After:**
[http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1861](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1861)

<img width="413" alt="bildschirmfoto 2016-08-10 um 19 14 06" src="https://cloud.githubusercontent.com/assets/1157669/17563506/0d75c39c-5f30-11e6-9c9d-8b1a32722243.png">

**Comment by plutonik-a** [comment]
@joewiz 
What about styling the unordered lists without the bullets?

**Comment by joewiz** [comment]
@plutonik-a Good catch, thanks! 

I'm indifferent about the bullets, but I think the link(s) should be indented.
