### ISSUE TITLE
Collapsed space between HTML elements

### ISSUE THREAD

**Issue by joewiz** [eXistSolutions/hsg-shell#58]
In cases where two HTML elements appear as adjoining siblings, such as `<em>` and `<a>`, the space between the two elements is collapsed. See this example from http://localhost:8080/exist/apps/hsg-shell/conferences:

> <img width="365" alt="screen shot 2015-12-13 at 5 25 20 pm" src="https://cloud.githubusercontent.com/assets/59118/11769827/ad223266-a1be-11e5-8a63-84624fc0439d.png">

The source HTML is in `pages/conferences/index.html` - see https://github.com/eXistSolutions/hsg-shell/blob/master/pages/conferences/index.html#L65-L67:

    <em>Foreign Relations of the United States series</em>
    <a href="$app/historicaldocuments/frus-history/events">Events</a>

The space between the original elements should be preserved.

**Comment by plutonik-a** [comment]
@joewiz 
The problem here simply was a missing blank character between the words.
As the linked word "Events" should not contain any blanks, you have to add it either to the preceding or following element.
`<a...>Events</a>`

Fixed with https://github.com/eXistSolutions/hsg-shell/commit/9d00b04d8c504d0e4e4beb5e6ebbb498db247f72
