### ISSUE TITLE
Page layout columns

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#67]
Improve layout: use separate columns for navigation arrows. Breadcrumbs, page title and main text body should be aligned vertically in one row.

**Comment by joewiz** [comment]
Related to this - to reiterate from our discussion today - please revert the `#content-inner` changes made in https://github.com/eXistSolutions/hsg-shell/commit/4cb44c13edbe0243ee71920af771baca3ee2cd65#diff-9ded89f5b82505fc5a2bfe420670fe6bR99.  We can return to considering a narrow width for certain pages in the future - but this change makes too many pages too narrow.

**Comment by JoernT** [comment]
i would rather prefer to have another look at it (probably together) - the old very wide column is really an issue form my point of view but it's easy to adjust the width of content-inner.

**Comment by joewiz** [comment]
Thanks for your concern about this, Joern, and readability in general. I think we should defer this width issue to 1.5. There are many more pressing style issues, as I see it. A careful comparison of each representative page from the old site with the new site is needed - lists, tables, sidebars, tables of contents, opener/seg alignment in FRUS documents (see the line beneath the document title, starting "No. 36" at https://history.state.gov/historicaldocuments/frus1947v07/d328; compare to the same at https://history.state.gov/beta/historicaldocuments/frus1947v07/d328). Obviously enhancements can be made - such as applying Bootstrap CSS table styles to tables (e.g., https://history.state.gov/beta/departmenthistory/travels/president/germany) - but I am wary of site-wide style changes whose effect on the site are difficult to anticipate at this stage. Parity is the focus from here on out for 1.0.

**Comment by JoernT** [comment]
@joewiz please allow a last attempt to convince you also because this has an effect on the prev/next navigation too - if text is very broad as before we get into trouble with placing the buttons - it's very easy to remove if you finally decide against it as it's only a sinlge CSS rule. I looked at many pages and i still see an improvement.

But we should probably really consider changing the grid consistently earlier as this is the much better approach. There would be a lot of changes but i think these can be made quite quickly - no more than 2 minutes per page once the right responsive classes are figured out. AND - would fix our navigation problem in one go.

And if you're still not happy it would be nice to point me to concrete examples. Thanks

**Comment by wolfgangmm** [comment]
I changed the grid and moved the navigation arrows into separate bootstrap columns. On small screens, a second set of arrows is shown next to the title.

Those changes are just meant for discussion. The concerns about readability etc. remain to be clarified.

**Comment by joewiz** [comment]
Fixing navigation is my top priority for this issue.  We will defer all max-width and readability changes to a future version, when all other pressing "old-site vs. new-site" styling issues have been addressed.  Wolfgang's proposal basically works, so please **(1)** apply that to all pages and **(2)** change the `#content-inner` CSS to remove all `max-width` restrictions, so that text occupies the full width of the div as specified in the col-md-* class attributes.  We'll tackle width-related readability issues in a future revision.

**Comment by JoernT** [comment]
done

**Comment by wolfgangmm** [comment]
All pages have been changed to use the new grid. On pages without navigation, the first left column is still left empty, so the main text does always appear indented by one column and 8 columns wide.

**Comment by joewiz** [comment]
This is good for launch. Thanks, @JoernT and @wolfgangmm.
