### ISSUE TITLE
harmonize styling rules for heading elements across static and dynamic pages

### ISSUE THREAD

**Issue by JoernT** [eXistSolutions/hsg-shell#73]
currently we use different heading stylings (h1,.... h6) for static pages (styled via global bootstrap styles) and dynamic pages (being output by tei simple).

Both stylesheets should be harmonized.

**Comment by JoernT** [comment]
found that this fact is responsible for other issues like the width of the reading area when displaying dynamic texts (which apply their additional margin) in comparison to static pages.

**Comment by plutonik-a** [comment]
Sure, we should encapsulate the styles for the dynamic content:
We can achieve this by adding generated IDs, or prefixed classnames for all elements, so we are able to identify each of the dynamic elements and override their style individually.

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/pull/156

**Comment by plutonik-a** [comment]
All relevant styles are represented by `hsg`-prefixed classnames.
The approach is encapsulating custom from vendor styles plus controlling the layout independently from the markup.

For example, I replaced hundreds of bootstrap `.col-*` classes from the templates for mainly 3 different `hsg-width-*` classes, which I extended with a set of relevant Bootstrap classes:

I did so with all other classes: 
Extract the Bootstrap styles with a `hsg-` prefixed custom-class and control the styles via stylesheet. 

The advantages are:
1. Reducing conflicts with custom-set Bootstrap classes coming from ODD or as inline-style.
2. Controlling the layout via stylesheet instead of "styling the markup" with static layout classes.
3. Modular approach via classname-variables and class-extensions results in easy maintence.
