### ISSUE TITLE
Scrolling on iphone/ipad

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#88]
Scrolling up/down on an iphone (and potentially android) does not work anymore, probably because the swipe left/right event is conflicting.

**Comment by dizzzz** [comment]
I think I have a similar issue in exide on my mac...... probably not related

**Comment by line-o** [comment]
@wolfgangmm is this issue still open?

**Comment by wolfgangmm** [comment]
I do not have any ios devices, sorry. On android swipe works as expected. Someone with an iphone/ipad has to fix this ;-)

**Comment by line-o** [comment]
It works - in a way - on an iOS device. Where is the expected behaviour (on mobile devices) described? 

For long content pages it feels unintuitive. We have a long content that is scrollable only in the rightmost edge of the screen, the arrows are positioned statically and therefore scroll out of view. 
Swiping then takes you somewhere else. On the next page, chapter or portion?

Would it be possible to fit the amount of text to the available screen size? That would definitely leverage the eBook experience. Assuming that is intended here.

**Comment by wolfgangmm** [comment]
I recently improved the code used here for one of the showcases, positioning the arrows at the very bottom edges on a mobile screen:

http://showcases.exist-db.org/exist/apps/eebo/works/A29001.xml?root=1.2.1.1.3.3&odd=teisimple.odd&view=div

Maybe we should adopt this code to hsg?

Limiting the amount of text to screen size is not possible and not desirable. If someone wants the ebook experience, he can get an epub instead.

**Comment by line-o** [comment]
That showcase works much better. Will adapt it/ fix possible markup or script issues.

**Comment by line-o** [comment]
Fix found here: https://github.com/mattbryson/TouchSwipe-Jquery-Plugin/issues/275
