### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by wolfgangmm** [eXistSolutions/hsg-shell#89]
http://localhost:8080/exist/apps/hsg-shell/search?q=%22united+states%22+AND+germany

generates an error

![image](https://cloud.githubusercontent.com/assets/607433/12122829/c71e0556-b3dd-11e5-81d6-8220766814fc.png)

**Comment by dizzzz** [comment]
The error makes no sense to me; My guesstimate is we het a bug in exist-db;

note that `frus:` is probably renamed to 'fh:' ; somewhere an old definition might be still hanging

**Comment by joewiz** [comment]
I'm stumped too.

**Comment by plutonik-a** [comment]
I've found another error message, when only searching for the string `!` (`/search?q=%21`):

```
<?xml version="1.0" ?><exception><path>/db/apps/hsg-shell/modules/view.xql</path><message>exerr:ERROR Syntax error in Lucene query string: Cannot parse '!': Encountered "<EOF>" at line 1, column 1.
Was expecting one of:
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
     [at line 145, column 29]
```

**Comment by plutonik-a** [comment]
This parsing problem always happens, when the search query is containing any of these strings, sometimes only when appearing as the first character:
 `+`, `"`, `(`, `)`, `/`, `\`, `:`, `-`, `{`, `}`, `[`, `]`, `~`

Also `*`, `?`:
`Syntax error in Lucene query string: Cannot parse '*': '*' or '?' not allowed as first character in WildcardQuery`

The same thing happens when searching these characters on the old site, so I assume, the Lucene queryyparser has to be fixed. I found this http://stackoverflow.com/questions/263081/how-to-make-the-lucene-queryparser-more-forgiving

**Comment by joewiz** [comment]
Good find! The methods in that article sound promising. Failing all else, a try-catch block is needed to shield users from this kind of error.

**Comment by joewiz** [comment]
I'm not seeing this error anymore: https://history.state.gov/search?q=%22united+states%22+AND+germany returns as expected.
