### ISSUE TITLE
Remove excessive spacing between editors' names from frus volume landing pages

### ISSUE THREAD

**Issue by tuurma** [eXistSolutions/hsg-shell#92]
Remove excessive spacing between editors' names from frus volume landing pages (extracted from #77) http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1969-76ve11p1

![landing](https://cloud.githubusercontent.com/assets/449468/12169411/2760ec1e-b530-11e5-9b31-ec015887a1a7.png)

**Comment by plutonik-a** [comment]
Fixed with https://github.com/eXistSolutions/hsg-shell/commit/5be5f161ec89d64402908b84a55cd0b324f48ed7

**Comment by plutonik-a** [comment]
I've just realized, that my fix did not solve the problem entirely.
The current markup is:
```
<div class="tei-titleStmt2">Editors:</div>
<ul class="tei-titleStmt4">
    <li>Halbert Jones</li>
    <li>Douglas Kraft</li>
</ul>

<div class="tei-titleStmt5">General Editor:</div>
<ul class="tei-titleStmt6">
    <li>Adam M. Howard</li>
</ul>
```

This could be optimized, because markup for "Editors" is semantically disconnected from the names.
If possible with the TEI classes, I would suggest to keep the old markup:
```
<dl>
    <dt>Editors:</dt>
    <dd>Halbert Jones</dd>
    <dd>Douglas Kraft</dd>
    <dt>General Editor:</dt>
    <dd>Adam M. Howard</dd>
</dl>
```
Until then, I will fix the spacing of this specific `<ul class="tei-titleStmt4">` only.

**Comment by plutonik-a** [comment]
Improved fix with https://github.com/eXistSolutions/hsg-shell/commit/03b30d88a8a48d2f502e66f710673841a12c0103
